#!/bin/bash

# Install all JupyterLab extensions in one shot to avoid multiple rebuilds

jupyter labextension install \
    @jupyter-widgets/jupyterlab-manager \
    jupyter-matplotlib \
    @jupyter-voila/jupyterlab-preview
